### ISSUE TITLE
Inject ILogger in a service.

### ISSUE THREAD

**Issue by DibranMulder** [Azure/azure-functions-dotnet-extensions#10]
Is it somehow possible to inject the `ILogger` into the constructor of a Service? I rather not pass on the instance, especially not when I have a multi layer (service / repository) pattern.

**Comment by ryanspletzer** [comment]
Please yes.

**Comment by kemmis** [comment]
+1

Does it work if we accept an ILoggerFactory in the constructors instead?

**Comment by ryanspletzer** [comment]
It looks like it will pass in an `ILoggerFactory` actually!

![image](https://user-images.githubusercontent.com/1481108/59037766-eb174a00-883f-11e9-93bf-dc58d8b13df3.png)

However in order to get the created logger to output to the functions host I had to adjust the category name to look like `Function.<FunctionName>.User` -- I found this category name by inspecting the ILogger that's provided in the function method:

![image](https://user-images.githubusercontent.com/1481108/59038582-3b42dc00-8841-11e9-9b6f-706dea2ea20c.png)

I'm *guessing* that the reason an ILogger is passed along today is because it retains the category name of the Function and the console / function host will only output logs for that function from the associated category... Which makes it a challenge if you are injecting a singleton service in multiple functions that you all want to have logs output from.

**Comment by ryanspletzer** [comment]
Ok I found `Microsoft.Azure.WebJobs.Logging.LogCategories` one of which I tested `Microsoft.Azure.WebJobs.Logging.LogCategories.Singleton` which is the string "Host.Singleton" -- this string is independent of what function execution you're in and will output logs to the function host.

![image](https://user-images.githubusercontent.com/1481108/59041364-6e3b9e80-8846-11e9-90c2-c8c20a612da9.png)

It would be nice to register one of these up front in Startup.cs so `ILogger` could just be injected everywhere vs. calling CreateLogger on the loggerFactory, but I suppose that the factory controls logger instance lifetime and would hope that a new `ILogger` is not being created everywhere for each call to the factory CreateLogger method. The instance likely just gets created once for the first call and then kept around for the lifetime of the running of the function host.

**Comment by ryanspletzer** [comment]
More info in comments in the code on LogCategories here:

https://github.com/Azure/azure-webjobs-sdk/blob/b798412ad74ba97cf2d85487ae8479f277bdd85c/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogCategories.cs

**Comment by ryanspletzer** [comment]
I think Host.Singleton is more to do with the singleton attribute which appears to be related to durable functions.

https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#singleton-attribute.

For now I've decided switched to this below, with a category that I create based on function name when I'm in the scope of a function itself (to be in line with the `ILogger` that was passed into the function method before), and another "Function.DependencyInjection" constructed category (or whatever arbitrary string you want) for creating `ILogger`'s in services created through DI. It's probably not perfect / ideal but works for now until we have an "official" approach for this.

![image](https://user-images.githubusercontent.com/1481108/59044689-962e0080-884c-11e9-9805-de8afb938c00.png)

![image](https://user-images.githubusercontent.com/1481108/59044718-a1812c00-884c-11e9-82e6-eb0452e60c56.png)

Prior to official release of this official DI extension when I had made my own DI extension binding based on various write-ups in the community, I was intercepting the service collection in the `IExtensionConfigProvider` and creating/registering a "DependencyInjection" categpry `ILogger` at that point from the logger factory which was available to services, and that was working just fine up to now, so this approach isn't too different from that, and finally lets me get off my own DI binding and onto the new one provided by Microsoft. :)

**Comment by brettsam** [comment]
Use `ILogger<T>` and you should get your logger injected. You'll need to explicitly allow your category (the full -- or even partial -- type name of `T`) through the filter due to: https://github.com/Azure/azure-functions-host/issues/4345

`ILogger` itself isn't supported (by default) in .NET Core DI.

Some updated comments/links with more details here: https://github.com/Azure/azure-functions-host/issues/2720#issuecomment-503627355

**Comment by fabiocav** [comment]
Closing this as the comment above addresses the issue.

**Comment by ryanspletzer** [comment]
Thank you for the guidance @brettsam!
