### ISSUE TITLE
Dotnet 6 and Azure Functions V4

### ISSUE THREAD

**Issue by toralux** [Azure/azure-functions-dotnet-extensions#67]
Now that Dotnet 6 is GA and both supports Azure Functions with OutOfProcess (dotnet-isolated) used in Dotnet 5 and InProcess (dotnet) used in Dotnet Core 3.1, we again need support for Startup-class and Dependency Injection for InProcess Dotnet 6 Azure Functions.

Any plan to support Dotnet 6 InProcess and Azure Fuctions V4?

**Comment by PhilippK13** [comment]
Are there any updates on this? If I'm reading this correctly this will prevent us from migrating to .net 6 if we want to benefit from dependency injection and use in-proc functions at the same time.

**Comment by dxynnez** [comment]
+1 here...I would love to use the out-of-process model (so that we don't rely on this package to do DI) but hey it doesn't support durable function which we heavily rely on...

This is just frustrating. I had to spend a noticeable amount of time trying to fill up all the missing pieces and gaps and only to find out although supporting net 6 has been claimed to be GA, it certainly is not.

**Comment by jsep925** [comment]
> Are there any updates on this? If I'm reading this correctly it will prevent us from migrating to .net 6 if we want to benefit from dependency injection and use in-proc functions at the same time.

Same here....

**Comment by dxynnez** [comment]
Just some update here... So we tried using the v1.1.0 'Microsoft.Azure.Functions.Extensions' with function app (in-process mode) targeting net 6 and it seems to be working well so far.

**Comment by brettsam** [comment]
Stale issue; this was completed long ago.
